server:
  port: 7081
spring:
  application:
    name: spring-cloud-feign-consumer
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone:  http://admin:admin123456@localhost:7070/eureka/
 #eureka.client.healthcheck.enabled=true只能在application.yml中设置。
 #设置bootstrap.yml中的值将导致不良副作用，例如在eureka中注册UNKNOWN状态。
    healthcheck:
      enabled: true
#eureka.instance.lease-renewal-interval-in-seconds
management:
    security:
      enabled: false
